package:
  name: conda-ci-test
  version: 0.1.0

source:
  - path: ..

build:
  number: 0
  binary_relocation: True
  rpaths:
    - lib/

outputs:
  - name: libnoop
    script: build_cpp_lib.sh

    requirements:
      build:
        - {{ compiler('c') }}
        - {{compiler('cxx')}}
        - libstdcxx-ng
        - libgcc-ng
        - fmt
        - cmake

      host:
        - fmt

      run:
        - fmt

  - name: noop
    script: build_python_pkg.sh

    requirements:
      build:
        - python
        - setuptools
        - build

      run:
        - python