name: Python Package Using Anaconda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        activate-environment: test
        environment-file: conda-recepie/environment.yml
        python-version: 3.9
        auto-activate-base: false
    - shell: bash -l {0}
      run: |
        conda info
        conda list
